export const IMAGES = {
  commissionsReferral: '/image/home/referral-commissions.png',
  commissionsReviewer: '/image/home/reviewer-commissions.png',
  commissionsSeller: '/image/home/seller-commissions.png',
  reviewer1: '/image/home/reviewer1.png',
  product1: '/image/home/product1.png',
  deal1: '/image/home/deal1.png',
  deal2: '/image/home/deal2.png',
  deal3: '/image/home/deal3.png',
  donation1: '/image/home/donation1.jpg', 
  donation2: '/image/home/donation2.jpg',
  donation3: '/image/home/donation3.jpg',
  donation4: '/image/home/donation4.jpg',
  donation5: '/image/home/donation5.jpg',
  donation6: '/image/home/donation6.jpg',
  donation7: '/image/home/donation7.jpg',
  heart1: '/image/home/heart1.svg', 
  heart2: '/image/home/heart2.svg', 
}
